### PR TITLE
only add a katello proxy box for el7

### PR DESCRIPTION
**Pull request by evgeni**
This PR is not a PR of honor... no highly esteemed deed is commemorated here... nothing valued is here.

And yet, it works.

Please revert this disgrace as soon as we can have EL8 proxies again.

### CODE REVIEW

**Comment by evgeni** [comment]
@ehelms so that took 30 minutes of time, but I don't know how many puppies will be killed because of it.

**Comment by ehelms** [comment]
@evgeni were you able to run through el7, and el8 install and upgrade tests locally? If not, I can run through a few.

**Comment by evgeni** [comment]
I only made the config generate properly, didn't run anything.

**Comment by evgeni** [comment]
i ran install pipes for el7/el8 and while el8 failed with an weird error that seems unrelated to the change here

**Comment by evgeni** [comment]
okay, the weird error I have been seein' on EL8 is fixed by https://github.com/theforeman/forklift/pull/1205 and unrelated

**Pull request merged**
