### PR TITLE
Sort imported and exported repositories before comparison

### PR DESCRIPTION
**Pull request by ehelms**
@jeremylenz here's a proposal to fix this, I kept hitting it testing something else so thought I'd throw an idea out there

### CODE REVIEW

**Comment by evgeni** [comment]
I like that!

Two thoughts:
* the file uses `$()` over ```` everywhere -- would be nice to keep that in sync
* I found the original error message rather "useless" -- if we put both (expected and given) in files, and run `diff` on them, instead of using `[ a = b ]`, we'd win a nice output for free (`diff` exists non-zero if there was a difference, so it's easy to use as a test, and I think we do that already in other places).

**Review by jturel — APPROVED** [review]
Worked for me :+1:

**Comment by ehelms** [comment]
Made @evgeni modifications, @jturel if you still have an environment to test again please do, I am re-spinning mine

**Comment by evgeni** [comment]
I would've done `hammer … | tr | sort > file` directly, without a variable and echo and stuff.

But wouldn't block on that :)

**Comment by jturel** [comment]
It still works! :1st_place_medal:

**Comment by jturel** [comment]
Hmm I'm seeing some later tests failing. Let me see why, but it seems unrelated.

```
 ✗ incremental update first component cv with composite propagation                                                                                                                                                                          
   (in test file fb-katello-content.bats, line 382)
     `hammer content-view version incremental-update --organization="${ORGANIZATION}" \' failed with status 70
   An error occurred incrementally updating the content view:
     Error: 502 Bad Gateway
 ✗ ensure component cv 1 version 1.1 has proper environments                                                                                                                                                                                 
   (in test file fb-katello-content.bats, line 389)
     `| grep "${CONTENT_VIEW_2} 1.1" | cut -d, -f1)' failed
 ✗ ensure composite cv version 1.1 has proper environments                                                                                                                                                                                   
   (in test file fb-katello-content.bats, line 397)
     `| grep "${CONTENT_VIEW_3} 1.1" | cut -d, -f1)' failed
 ✗ ensure component cv 1 latest version has proper content                                                                                                                                                                                   
   (in test file fb-katello-content.bats, line 406)
     `| grep "${CONTENT_VIEW_2} 1.1" | cut -d, -f1)' failed
 ✓ ensure component cv 2 latest version has proper content                                                                                                                                                                                   
 ✗ ensure composite cv latest version has proper content                                                                                                                                                                                     
   (in test file fb-katello-content.bats, line 448)
     `| grep "${CONTENT_VIEW_3} 1.1" | cut -d, -f1)' failed

```

**Comment by jturel** [comment]
```
[root@pipe-katello-server-nightly-centos7 bats]# bats fb-katello-content.bats                                                                                                                                                            
 ✓ Create an Empty Organization                                                                                                                                                                                                              
 ✓ create an Organization                                                                                                                                                                                                                    
 ✓ create a product                                                                                                                                                                                                                          
 ✓ create package repository                                                                                                                                                                                                                 
 ✓ upload package                                                                                                                                                                                                                            
 ✓ sync repository                                                                                                                                                                                                                           
 ✓ create a file repository                                                                                                                                                                                                                  
 ✓ sync file repository                                                                                                                                                                                                                      
 ✓ fetch file from file repository                                                                                                                                                                                                           
 ✓ create a container repository                                                                                                                                                                                                             
 ✓ sync container repository                                                                                                                                                                                                                 
 - create puppet repository (skipped: Puppet content is not available in scenarios with only Pulp 3)                                                                                                                                         
 - upload puppet module (skipped: Puppet content is not available in scenarios with only Pulp 3)                                                                                                                                             
 ✓ create lifecycle environment                                                                                                                                                                                                              
 ✓ create content view                                                                                                                                                                                                                       
 ✓ add yum repo to content view                                                                                                                                                                                                              
 ✓ publish content view                                                                                                                                                                                                                      
 ✓ promote content view                                                                                                                                                                                                                      
 ✓ export content view version                                                                                                                                                                                                               
 ✓ create skeleton org for import                                                                                                                                                                                                            
 ✓ import the exported content view                                                                                                                                                                                                          
 ✓ compare contents of export and import                                                                                                                                                                                                     
 ✓ export the library                                                                                                                                                                                                                        
 ✓ create org for library import                                                                                                                                                                                                             
 ✓ import the library to the new organization                                                                                                                                                                                                
 ✓ compare contents of library export and import                                                                                                                                                                                             
 ✓ publish content view again                                                                                                                                                                                                                
 ✓ perform an incremental export                                                                                                                                                                                                             
 ✓ perform an incremental library export                                                                                                                                                                                                     
 ✓ create activation key                                                                                                                                                                                                                     
 ✓ disable auto-attach                                                                                                                                                                                                                       
 ✓ add subscription to activation key                                                                                                                                                                                                        
 - add puppet module to content view (skipped: Puppet content is not available in scenarios with only Pulp 3)                                                                                                                                
 ✓ promote first content view again                                                                                                                                                                                                          
 ✓ create and sync modules-rpms repo                                                                                                                                                                                                         
 ✓ create and sync rpm-deps repo                                                                                                                                                                                                             
 ✓ create first component content view                                                                                                                                                                                                       
 ✓ add yum and docker repos to first component content view                                                                                                                                                                                  
 ✓ add errata exclude filter to first component content view                                                                                                                                                                                 
 ✓ add package exclude filter to first component content view                                                                                                                                                                                
 ✓ add module include filter to first component content view                                                                                                                                                                                 
 ✓ publish first component content view                                                                                                                                                                                                      
 ✓ create composite content view                                                                                                                                                                                                             
 ✓ publish and promote composite content view
 ✓ incremental update first component cv with composite propagation
 ✓ ensure component cv 1 version 1.1 has proper environments
 ✓ ensure composite cv version 1.1 has proper environments
 ✓ ensure component cv 1 latest version has proper content
 ✓ ensure component cv 2 latest version has proper content
 ✓ ensure composite cv latest version has proper content
 ✓ fetch rpm from yum repository on old path

51 tests, 0 failures, 3 skipped
```

**Comment by ehelms** [comment]
> I would've done `hammer … | tr | sort > file` directly, without a variable and echo and stuff.
> 
> But wouldn't block on that :)

I'll let you do it that way :) I just prefer not to crowd the in field.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
