### PR TITLE
Drop --upgrade explicitly on 3.17+ upgrade

### PR DESCRIPTION
**Pull request by ehelms**
Current cause of 3.17 RC1 release failure.

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Is this an issue on older installs? In upstream we have 3.15 and 3.16 supported, which means we also upgrade to 3.14. AFAIK it was still needed there so any 3.15.z release may break?

**Comment by evgeni** [comment]
Does it? https://www.github.com/theforeman/forklift/tree/master/roles%2Fforeman_installer%2Ftasks%2Fupgrade.yml adds --upgrade on these old versions, so it should be safe to drop it here?

**Comment by ekohl** [comment]
If that's true, then also `--certs-update-all` is redundant.

**Comment by evgeni** [comment]
That's probably correct. Let's drop the offending `--upgrade`, see that it works and clean up afterwards.

**Review by evgeni — APPROVED** [review]

**Pull request merged**
