### PR TITLE
Move qpid to Dockerfile

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
[test containers]

**Comment by carbonin** [comment]
Was there supposed to be a qpid Dockerfile in here also? Or are you pulling from a different image?

**Comment by ehelms** [comment]
@carbonin Dunno where that got off to put good catch, I put in the missing Dockerfile

**Comment by carbonin** [comment]
Can you also remove the `qpid` role? (Same concern as https://github.com/theforeman/forklift/pull/717#issuecomment-392817713)

**Comment by ehelms** [comment]
@carbonin Check and done.

**Pull request merged**
