### PR TITLE
fix foreman version check in verify packages

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ekohl** [comment]
This will break until https://github.com/theforeman/foreman-packaging/pull/5257 is resolved and picked into 2.*.

**Comment by evgeni** [comment]
that's the intention, well, we should fix it, and then merge this :)

**Comment by ekohl** [comment]
Just making sure that people who didn't follow our IRC conversation also know and don't just merge this :)

**Comment by evgeni** [comment]
2.0 and 2.1 are fixed

**Pull request merged**
