### PR TITLE
Don't run with --upgrade in content proxy upgrade

### PR DESCRIPTION
**Pull request by tbrisker**

### CODE REVIEW

**Comment by tbrisker** [comment]
In that case, I'm afraid  don't know how to accomplish it, i'm not familiar enough with how all these roles and playbooks come together in the ci pipelines

**Comment by ehelms** [comment]
Yes, this will need a version check to ensure previous upgrades continue to work. Here is an example of how we did it:

https://github.com/theforeman/forklift/blob/master/roles/foreman_installer/tasks/upgrade.yml#L12

**Comment by tbrisker** [comment]
My ansible knowledge is quite limited, but wouldn't that generic upgrade task already take care of it since it's included in this task?

**Comment by ekohl** [comment]
I had a look a while back gave up on fixing it since the Ansible flow in combination with the Katello upgrade drove me insane. Dropping the need for special casing Katello upgrades will fix it in the long run.

**Comment by evgeni** [comment]
#1197 was merged

**Pull request closed without merging**
