### PR TITLE
Build and deploy Foreman via a foreman-operator

### PR DESCRIPTION
**Pull request by ehelms**
This changes moves the deployment model to be handled by an Operator based on the [ansible-operator](https://github.com/shawn-hurley/ansible-operator) to create and manage resources from within the cluster. An operator can be thought as a way to manage the state of the application in a Kube-native way. The operator monitors instances of the Foreman custom resource and reconciles the state of all entities based on the definition. An example of this in action:

By default, the following is true:

```
$ oc get pods | grep pulp-worker
pulp-worker-589b4f8cf9-nktnn             1/1       Running     0          12m
pulp-worker-589b4f8cf9-zvt6h             1/1       Running     0          12m
```

Now if we edit `cr.yaml` to the following:

```
apiVersion: app.theforeman.org/v1alpha1
kind: Foreman
metadata:
  name: "myforeman"
  namespace: foreman
spec:
  application_hostname: foreman.192.168.42.83.nip.io
  pulp_worker_count: 3
```

And apply the changes:

```
oc apply -f cr.yaml
```

We will find the following true after some time:

```
ehelms@war containers (operator)$ oc get pods | grep worker
pulp-worker-589b4f8cf9-nktnn             1/1       Running     0          13m
pulp-worker-589b4f8cf9-s79bp             1/1       Running     0          49s
pulp-worker-589b4f8cf9-zvt6h             1/1       Running     0          13m
```

### CODE REVIEW

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by ehelms** [comment]
[test containers]

**Comment by fabianvf** [comment]
@ehelms any update? Happy to help handle any updates you need for more recent releases of the Ansible Operator

**Pull request closed without merging**
