### PR TITLE
fixes(906) - Add docker provider

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by bmbouter** [comment]
I tested this using pulplift, but I ran into an error. I don't think the issue is in this PR though. The base image we are using is not compatible w/ the docker backend. We need to look at how pulp/devel does it.

I ran `vagrant up --provider docker pulp3-source-fedora28` and I got

```
Name: fedora/28-cloud-base
Address: https://vagrantcloud.com/fedora/28-cloud-base
Requested provider: [:docker]
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: fedora/28-cloud-base
Address: https://vagrantcloud.com/fedora/28-cloud-base
Requested provider: [:docker]
```

**Comment by ehelms** [comment]
I'd suggest we make some base level docker images in Pulplift's boxes deinfitions, e.g.

```
container-fedora28:
  image: 'fedora:28'
```

If this needs to support Pulp devel building a container then we shoudl also define some base boxes that specify the build arguments.

**Comment by pavelpicka** [comment]
Trying on OSX, and when create some basic "box definition" 
```
pulp3-docker-fedora28:
  image: 'fedora:28'
  memory: 2048
```
in `vagrant/boxes.d/40-containers.yaml` and run `vagrant up pulp3-docker-fedora28 --provider docker` I got 
```
There are errors in the configuration of this machine. Please fix
the following errors and try again:

docker provider:
* One of "build_dir" or "image" must be set
```

may I put on wrong place?

**Comment by ehelms** [comment]
There was a bug in my code. Please re-test.

**Comment by bmbouter** [comment]
I went to retest this again and it didn't work for me. I checked out the updated PR for forklift. I also am using the latest from pulplift which defines these boxes:  https://github.com/pulp/pulplift/blob/master/vagrant/boxes.d/40-containers.yaml 

`vagrant up pulp3-containers-fedora28 --provider docker`

It's complaining about the image types again. It is using the docker backend. I get this output.

```
/usr/share/vagrant/gems/gems/vagrant-2.0.2/lib/vagrant/action/builtin/box_add.rb:221:in `add_from_metadata': The box you're attempting to add doesn't support the provider (Vagrant::Errors::BoxAddNoMatchingProvider)
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: fedora/28-cloud-base
Address: https://vagrantcloud.com/fedora/28-cloud-base
Requested provider: [:docker]
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: fedora/28-cloud-base
Address: https://vagrantcloud.com/fedora/28-cloud-base
Requested provider: [:docker]
```

The issue I think is in the pulplift defined boxes, but I'm not sure how to adjust them.

**Comment by ehelms** [comment]
@dkliban is this something you still need?

**Pull request closed without merging**
