### PR TITLE
gather facts about server before running smoker

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by ehelms** [comment]
What is this needed to help with?

**Comment by evgeni** [comment]
> What is this needed to help with?

Fixing the breakage I produced in https://github.com/theforeman/forklift/pull/1258 while trying to get smoker to work on non-nightly.

**Review by ekohl — APPROVED** [review]
Might be nice to describe why it's needed in the commit message, but :+1: in general.

**Comment by evgeni** [comment]
updated commit message, thanks!

**Pull request merged**
