### PR TITLE
Stop installing katello on proxies

### LINKED ISSUE #1025: make install pipeline not use katello role on proxy
This is probably also incorrect and might pull in `katello` as a `foreman_installer_additional_packages` on the proxy.

Additionally we should probably skip the client repos on Foreman as well since those are supposed to be optional but that's for another PR.

_Originally posted by @ekohl in https://github.com/theforeman/forklift/pull/968/files_

### PR DESCRIPTION
**Pull request by ekohl**
This leverages the fact that Ansible variables can be set on a box via vagrant. Since vagrant is used as an inventory, these variables are available during the entire run. By doing so, the need for separate _server and _proxy vars files is removed.

There is also a patch that fixes a bug in forklift's ansible variable handling.

Fixes #1025
Alternative to #1118

### CODE REVIEW

**Comment by ekohl** [comment]
When I tested this out, I still had an issue where the disable-system-checks was not set properly, setting it back to WIP. I've opened https://github.com/theforeman/forklift/pull/1121 and https://github.com/theforeman/forklift/pull/1122 as separate PRs so they can be merged.

**Comment by ekohl** [comment]
> I still had an issue where the disable-system-checks was not set properly

Fixed by setting the base variables on the proxy box. Should be ready now.

**Comment by ehelms** [comment]
I'll handle merge and monitoring of jobs. Going to wait until the mashing issues are fixed first.

**Comment by jturel** [comment]
I think this PR has broken running the pipeline locally for me although it looks like CI isn't affected. The pipeline installer run is using `--scenario foreman` rather than `--scenario katello` It's as if the vars in the generated boxes.yaml is ignored (I see `foreman_installer_scenario: katello` there)

Running this command:
```
ansible-playbook pipelines/upgrade_pipeline.yml -e forklift_state=up -e pipeline_os=centos7 -e pipeline_type=katello -e pipeline_version=nightly
```
```
[jturel@strangeways forklift]$ rpm -q python2
python2-2.7.17-1.fc31.x86_64
[jturel@strangeways forklift]$ rpm -q python3
python3-3.7.6-2.fc31.x86_64
[jturel@strangeways forklift]$ rpm -q ansible
ansible-2.9.5-1.fc31.noarch
```

**Comment by ehelms** [comment]
Yep, this was broken for a day or so. Latest master of forklift shouldn't run into this.

**Comment by jturel** [comment]
> Yep, this was broken for a day or so. Latest master of forklift shouldn't run into this.

I am seeing it on latest master :-/

**Comment by ekohl** [comment]
@jturel have you by any chance not (re)created the machines? What does `./bin/ansible-vars [HOSTNAME]` show? (might want to pipe it through jq for readable JSON).

**Comment by jturel** [comment]
They were all new boxes. But I think I see the problem:

```
[jturel@strangeways forklift]$ ./bin/ansible-vars centos7-katello-3.15                                                                                        
Traceback (most recent call last):                                                                                                                            
        10: from ./bin/ansible-vars:7:in `<main>'                                                                                                             
         9: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'                                
         8: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'                                                                      
         7: from /home/jturel/code/forklift/vagrant/lib/forklift.rb:6:in `<top (required)>'      
         6: from /home/jturel/code/forklift/vagrant/lib/forklift.rb:6:in `each'                                                                               
         5: from /home/jturel/code/forklift/vagrant/lib/forklift.rb:6:in `block in <top (required)>'
         4: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
         3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
         2: from /home/jturel/code/forklift/vagrant/lib/forklift/compat.rb:6:in `<top (required)>'
         1: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- deep_merge (LoadError)
```

I get JSON after I installed the deep_merge gem. Trying the pipeline now

**Comment by jturel** [comment]
Well I got an error while running the installer but it was definitely installing Katello. Thanks for the pointer @ekohl

**Pull request merged**
