### PR TITLE
Addresses 1036 - Add support for a katello-hammer-devel all-in-one box.

### PR DESCRIPTION
**Pull request by jeffmcutter**
https://github.com/theforeman/forklift/issues/1036

### CODE REVIEW

**Comment by ehelms** [comment]
Sorry for the long delay reviewing. Is this intended to be a hammer development box? Or a katello development box that also has hammer setup via git for development as well? If it's the latter, I think we could opt to add a variable and conditional inclusion of `hammer_devel` in the normal devel box.

**Comment by jeffmcutter** [comment]
The use case was to develop hammer content-view version export/import which needs to be run on the katello server to work.  That being said, it seems that content-view version import/export is deprecated with Pulp 2.  I'm not sure what the situation is for Pulp 3.  Perhaps this isn't useful at all anymore, would need to research how the import/export works with Pulp 3.

https://github.com/Katello/hammer-cli-katello/pull/718

**Comment by ekohl** [comment]
Hammer is supposed to be 100% remote and that content view part was IMHO always a bug. With Pulp 3 we're making steps forward. I'm not sure how far it is and what the exact current design is, but maybe @jjeffers or @jturel can point to the correct issue.

**Comment by jturel** [comment]
> The use case was to develop hammer content-view version export/import which needs to be run on the katello server to work. That being said, it seems that content-view version import/export is deprecated with Pulp 2. I'm not sure what the situation is for Pulp 3. Perhaps this isn't useful at all anymore, would need to research how the import/export works with Pulp 3.
> 
> [Katello/hammer-cli-katello#718](https://github.com/Katello/hammer-cli-katello/pull/718)

Hey @jeffmcutter ! We just released Katello 4.0 which has all of the new pulp3-based import/export functionality. Upstream docs should reflect the new hammer commands `hammer content-export` and `hammer content-import`. Even better news is that both of those commands should be able to be executed via hammer either on the Katello server itself or external.

**Comment by jeffmcutter** [comment]
Thanks for the confirmation.  Seems this PR isn't very useful anymore.  I'll go ahead and close it.  Thanks!

**Pull request closed without merging**
