### PR TITLE
Add Centos9 Stable devel json, kickstart and remove centos7 packer

### PR DESCRIPTION
**Pull request by chris1984**
Proof that it is creating and publishing like it should:

https://app.vagrantup.com/katello/boxes/katello-devel

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Review by ehelms — APPROVED** [review]

**Comment by nadjaheitmann** [comment]
Thanks to all of you for maintaining this! Is it possible to spin up the new stable box, already? I did not find it in the `vagrant/boxes.d/99-local.yaml.example` and I don't know the workflows here :)

**Comment by nadjaheitmann** [comment]
Actually, the one I want is the stable one. So I am waiting for `vagrant up centos9-katello-devel-stable` to work

**Comment by chris1984** [comment]
Looks like I need to update https://github.com/theforeman/forklift/blob/master/vagrant/boxes.d/99-local.yaml.example#L95 I will do that in a new PR

**Comment by chris1984** [comment]
> Actually, the one I want is the stable one. So I am waiting for `vagrant up centos9-katello-devel-stable` to work

Made the PR here - https://github.com/theforeman/forklift/pull/1834

**Pull request merged**
