### PR TITLE
use correct chrony.conf

### PR DESCRIPTION
**Pull request by mmoll**

### CODE REVIEW

**Comment by mmoll** [comment]
completely untested :bomb:

**Comment by tbrisker** [comment]
Looks like the issue isn't the distro but rather the file that doesn't contain the string 'puppet' - https://github.com/theforeman/forklift/pull/1146#pullrequestreview-396275130

**Comment by mmoll** [comment]
@tbrisker Both issues need fixing, AFIACT.

**Comment by ehelms** [comment]
Could we do a more puppety test where we stop the service or remove a file, run puppet and then check that it exists again? Or do that form the get go?

**Comment by ehelms** [comment]
Let's revert for now to keep EL7 going. https://github.com/theforeman/forklift/pull/1148

**Comment by ehelms** [comment]
This is the chrony module (https://github.com/voxpupuli/puppet-chrony)  so we could propose adding the template header to it and then use it?

**Comment by ekohl** [comment]
I also considered something like that, but relying on some complex module might be too much. Publishing a dummy module that statically manages something is much easier. It can be as simple as creating `/file-managed-by-puppet`

**Comment by ehelms** [comment]
Proposed set of changes here: https://github.com/theforeman/foreman-infra/pull/1341

**Comment by evgeni** [comment]
@mmoll closing in favor of @ehelms solution? :)

**Comment by mmoll** [comment]
Ja. :)

**Pull request closed without merging**
