### PR TITLE
update foreman-maintain before stopping services

### PR DESCRIPTION
**Pull request by evgeni**
This ensures any possible fixes for process handling are available.

### CODE REVIEW

**Comment by evgeni** [comment]
I am unsure I want to keep this forever (as it's how a Satellite upgrade works under the hood) and update our docs, or just use it to test the fix for https://community.theforeman.org/t/katello-nightly-rpm-pipeline-2155-failed/39693/ and backport the actual fix to the 1.7.z branch afterwards.

**Review by ehelms — APPROVED** [review]

**Review by ekohl — APPROVED** [review]
I'd like to avoid keeping this forever.

In fact, what I'd prefer is that we find a solution where we don't need foreman-maintain at all to stop the services. I've always wonder if we can define a `foreman.target` and somehow get `systemd` to do the hard work.

**Comment by evgeni** [comment]
https://github.com/theforeman/foreman_maintain/pull/942

**Comment by evgeni** [comment]
https://github.com/theforeman/forklift/pull/1867

**Pull request merged**
