### PR TITLE
Add Fedora39 and Fedora40 boxes

### PR DESCRIPTION
**Pull request by wbclark**

### CODE REVIEW

**Comment by wbclark** [comment]
https://github.com/theforeman/forklift/pull/1831 should make the linter happy

**Comment by wbclark** [comment]
I rebased this, but the checks aren't starting. Going to try closing and re-opening.

**Comment by wbclark** [comment]
Ah, it's a known issue: https://www.githubstatus.com/

**Review by chris1984 — APPROVED** [review]
Looks good to me @ehelms can this get a merge please?

**Pull request merged**
