### PR TITLE
properly parse centos-stream version

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Review by ekohl — COMMENTED** [review]
Makes me wonder if we should source `/etc/os-release` and use that:
```bash
tSetOSVersion() {
  if [[ -z "$OS_VERSION" ]]; then
    . /etc/os-release
    OS_VERSION=$VERSION_ID
  fi
}
```

**Comment by evgeni** [comment]
Maybe? You'd still need the `grep -o '^[0-9]*'` part, as on RHEL VERSION_ID is actually of the form X.Y, not X.

**Comment by evgeni** [comment]
Let's get the known working fix in and then see how we refactor it?

**Review by ekohl — APPROVED** [review]
Fair enough.

**Pull request merged**
