### PR TITLE
use quay.io/foreman/busybox-test for container tests

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
@jlsherrill @ianballou do you know why the "pull container" test fails with:

```
   Trying to pull centos7-katello-3-17.yatsu.example.com/test_organization-test_product-foremanbusybox...
     error parsing HTTP 404 response body: invalid character ':' after top-level value: "404: Not Found"
   Error: error pulling image "centos7-katello-3-17.yatsu.example.com/test_organization-test_product-foremanbusybox": unable to pull centos7-katello-3-17.yatsu.example.com/test_organization-test_product-foremanbusybox: unable to pull image: Error initializing source docker://centos7-katello-3-17.yatsu.example.com/test_organization-test_product-foremanbusybox:latest: Error reading manifest latest in centos7-katello-3-17.yatsu.example.com/test_organization-test_product-foremanbusybox: error parsing HTTP 404 response body: invalid character ':' after top-level value: "404: Not Found"
```

all other container related tests seem to pass.

`production.log` "agrees":

```
2020-11-25T09:04:24 [I|app|6ee94744] Started GET "/v2/test_organization-test_product-foremanbusybox/manifests/latest" for 127.0.0.1 at 2020-11-25 09:04:24 +0000
2020-11-25T09:04:25 [I|app|6ee94744] Processing by Katello::Api::Registry::RegistryProxiesController#pull_manifest as 
2020-11-25T09:04:25 [I|app|6ee94744]   Parameters: {"repository"=>"test_organization-test_product-foremanbusybox", "tag"=>"latest"}
2020-11-25T09:04:25 [E|app|6ee94744] RestClient::NotFound: 404 Not Found
Body: 404: Not Found
```

**Comment by evgeni** [comment]
if I run the full pipeline it works… what?! :)

**Comment by evgeni** [comment]
Running it again, the digests are in a different order, but the same:
```
    # Error: PLP0000: The Manifest digest does not match the expected value. The remote feed announced a digest of sha256:13280b5914050853a87d662c3229d42b61544e36dd4515f06e188835f3407468, but the downloaded digest was sha256:fc5dcad1472b8d34fe1bd242d160f1a337f3c5a2f22c28169656d13e3a14acb4.
    # PLP0000: The Manifest digest does not match the expected value. The remote feed announced a digest of sha256:13280b5914050853a87d662c3229d42b61544e36dd4515f06e188835f3407468, but the downloaded digest was sha256:f389f3a04fa07bca55074cafefe2a70a7b562974ba83c8642d979d003be21abf.
    # PLP0000: The Manifest digest does not match the expected value. The remote feed announced a digest of sha256:13280b5914050853a87d662c3229d42b61544e36dd4515f06e188835f3407468, but the downloaded digest was sha256:087ebbb66938dbac6031b01c006dae2e56b5e836c2a00b08398552273c9396ce.
```

**Comment by evgeni** [comment]
and it works fine on katello 3.16…

**Comment by ekohl** [comment]
> do you know why the "pull container" test fails with

Yesterday quay had an outage: https://status.quay.io/

**Comment by evgeni** [comment]
> Yesterday quay had an outage: https://status.quay.io/

But shouldn't then the "sync" step also fail?

**Comment by ekohl** [comment]
It was degraded:
> Users may experience increased latency and error rates during image pulls and pushes.
I think we can assume the issues you saw were due to that.

**Comment by evgeni** [comment]
given this works fine on 3.16, 3.17 and 3.18, marking as ready for review

**Review by ekohl — APPROVED** [review]

**Comment by evgeni** [comment]
Thanks!

I've opened https://projects.theforeman.org/issues/31401 for the proxy sync issue

And found https://projects.theforeman.org/issues/31362 for the 404 I've been seeing.

Merging this as I think the sync issue is not something I created here ;)

**Pull request merged**
