### PR TITLE
Enable Pulp 3 for devel installs

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@jlsherrill this should remove the need for your PR

**Comment by ehelms** [comment]
@sjha4 https://github.com/theforeman/puppet-katello_devel/pull/225 is the PR to fix the issue this introduces

**Comment by sjha4** [comment]
I saw this http://pastebin.test.redhat.com/837590 running this. I do have this https://github.com/theforeman/puppet-katello_devel/commit/254df33b1216539426c92bf7280e8d2221d98ba5 on the dev box.

**Comment by ekohl** [comment]
@sjha4 that looks like it was deployed with a too old foreman-installer that didn't include the right patches.

**Comment by sjha4** [comment]
@ekohl : On my dev box I have this 
`foreman-installer-2.1.0-0.1.develop.20200217031733gite4b56a0.el7.noarch` Is there a later version I should move to which has the above commit?

**Comment by ekohl** [comment]
Looks like nightly wasn't promoted due to an issue with the DB. Foreman develop has been fixed, but you'll need to wait for a nightly after yesterday (20200218 or newer) I think.

**Comment by laviro** [comment]
I had an issue with the installer on luna machine, yum couldn't install `pulpcore-selinux`,
just checkout out to the commit before this PR got merged and the installer succeed,
not sure if pulp3 is the problem, can you try and confirm? thanks

**Comment by ehelms** [comment]
Do you have the full error output?

**Comment by laviro** [comment]
I didn't save it, but I can try to reproduce it if you want

**Pull request merged**
