### PR TITLE
Omit bats test for registration instead of using empty string

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Review by evgeni — COMMENTED** [review]
Omit only works for module parameters, not array entries

**Comment by evgeni** [comment]
You'll need something like https://github.com/theforeman/forklift/blob/279f047780a2d9d5936f9a45234e19606e37e2b0/pipelines/vars/forklift_pulpcore.yml#L23

**Comment by jlsherrill** [comment]
oh ignore me, i see your change is more involved, let me do that instead!

**Review by evgeni — APPROVED** [review]

**Comment by jlsherrill** [comment]
my 4.0 test run passed (well smoker failed, but unrelated)

**Pull request merged**
