### PR TITLE
Add module_hotfixes=1 for pulpcore repositories

### PR DESCRIPTION
**Pull request by ehelms**
I got this for you @evgeni 

```
16:00:25  [0;31m    2021-07-08 19:49:24 [NOTICE] [configure] Starting system configuration.[0m
16:00:25  [0;31m    2021-07-08 19:50:44 [NOTICE] [configure] 250 configuration steps out of 1888 steps complete.[0m
16:00:25  [0;31m    2021-07-08 19:51:46 [NOTICE] [configure] 500 configuration steps out of 1890 steps complete.[0m
16:00:25  [0;31m    2021-07-08 19:51:48 [NOTICE] [configure] 750 configuration steps out of 1892 steps complete.[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] Execution of '/bin/dnf -d 0 -e 1 -y install python3-pulp-ansible' returned 1: Error:[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] Problem: package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint >= 5.0.8, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint < 6.0, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package ansible-lint-5.0.8-1.el8.noarch requires python3-rich >= 9.5.1, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-pulp-ansible-1:0.8.0-1.el8.noarch requires python3-galaxy-importer >= 0.3.1, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-rich-10.0.1-1.el8.noarch requires python3-pygments >= 2.6.0, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - conflicting requests[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-pygments-2.8.1-1.el8.noarch is filtered out by modular filtering[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] /Stage[main]/Pulpcore::Plugin::Ansible/Pulpcore::Plugin[ansible]/Package[python3-pulp-ansible]/ensure: change from 'purged' to 'present' failed: Execution of '/bin/dnf -d 0 -e 1 -y install python3-pulp-ansible' returned 1: Error:[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] Problem: package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint >= 5.0.8, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint < 6.0, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package ansible-lint-5.0.8-1.el8.noarch requires python3-rich >= 9.5.1, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-pulp-ansible-1:0.8.0-1.el8.noarch requires python3-galaxy-importer >= 0.3.1, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-rich-10.0.1-1.el8.noarch requires python3-pygments >= 2.6.0, but none of the providers can be installed[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - conflicting requests[0m
16:00:25  [0;31m    2021-07-08 19:52:06 [ERROR ] [configure] - package python3-pygments-2.8.1-1.el8.noarch is filtered out by modular filtering[0m
16:00:25  [0;31m    2021-07-08 19:52:19 [NOTICE] [configure] 1000 configuration steps out of 1898 steps complete.[0m
16:00:25  [0;31m    2021-07-08 19:52:23 [NOTICE] [configure] 1250 configuration steps out of 1919 steps complete.[0m
16:00:25  [0;31m    2021-07-08 19:58:46 [NOTICE] [configure] 1500 configuration steps out of 1919 steps complete.[0m
16:00:25  [0;31m    2021-07-08 20:00:08 [NOTICE] [configure] 1750 configuration steps out of 1919 steps complete.[0m
16:00:25  [0;31m    2021-07-08 20:00:12 [NOTICE] [configure] System configuration has finished.[0m
```

### CODE REVIEW

**Comment by ehelms** [comment]
This is modeled off our previous approach https://github.com/theforeman/forklift/blob/master/roles/foreman_repositories/tasks/redhat_staging_repos.yml

**Comment by evgeni** [comment]
My memory says, that doesn't work?

Did you test it?

**Comment by evgeni** [comment]
```console
[root@93307445641c /]# cat /etc/yum.repos.d/pulpcore.repo 
[pulpcore-repository]
name=Pulpcore 3.14
baseurl=https://yum.theforeman.org/pulpcore/3.14/el8/x86_64/
gpgcheck=0
include=/etc/yum/pulpcore.conf
[root@93307445641c /]# cat /etc/yum/pulpcore.conf         
module_hotfixes=1
[root@93307445641c /]# yum install python3-galaxy-importer
Failed to set locale, defaulting to C.UTF-8
Last metadata expiration check: 0:00:26 ago on Fri Jul  9 05:14:39 2021.
Error: 
 Problem: package ansible-lint-5.0.8-1.el8.noarch requires python3-rich >= 9.5.1, but none of the providers can be installed
  - package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint >= 5.0.8, but none of the providers can be installed
  - package python3-galaxy-importer-0.3.2-1.el8.noarch requires ansible-lint < 6.0, but none of the providers can be installed
  - package python3-rich-10.0.1-1.el8.noarch requires python3-pygments >= 2.6.0, but none of the providers can be installed
  - conflicting requests
  - package python3-pygments-2.8.1-1.el8.noarch is filtered out by modular filtering
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Nope, nope, nope :(

**Comment by evgeni** [comment]
So there are a few possibilities there. And none are pretty.

1. ansible-core 2.11 actually can set modules_hotfixes via the `yum_repository` module (https://github.com/ansible/ansible/pull/70042), but ain't nobody has ansible-core 2.11 unless they are installing from `pip`
2. use a template like we did in `pulp_installer` after we realized `include` doesn't work: https://github.com/pulp/pulp_installer/pull/586
3. use something like the following (not idempotent, but given it only affects installs from koji, I don't care):
```yaml
    - name: "Add Pulpcore {{ pulpcore_repositories_version }} repository"
      yum_repository:
        name: pulpcore-repository
        description: Pulpcore {{ pulpcore_repositories_version }}
        baseurl: "https://yum.theforeman.org/pulpcore/{{ pulpcore_repositories_version }}/el{{ ansible_distribution_major_version }}/x86_64/"
        gpgcheck: no
        enabled: yes
    - name: Set module_hotfixes=1 for pulpcore
      lineinfile:
        path: /etc/yum.repos.d/pulpcore-repository.repo
        line: module_hotfixes=1
```

**Comment by evgeni** [comment]
I've implemented 3 in https://github.com/theforeman/forklift/pull/1381

**Comment by evgeni** [comment]
Closing, as we've merged #1381 now

**Pull request closed without merging**
