### PR TITLE
bats: Configure hammer and use that configuration

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by ekohl** [comment]
Still missing is the pipeline changes to set the proper host as environment variable, but that's already broken.

**Comment by ehelms** [comment]
I thought the installer configured all of this for us as of [1]?

[1] https://github.com/Katello/katello-installer/commit/730de817f3681978ba5efc33b7394337719aa577

**Comment by ekohl** [comment]
That's the katello scenario, not the proxy.

**Comment by ehelms** [comment]
Ahhh, but the hammer setup is being for all tests. Maybe the proxy tests should be just run on the server? They don't appear to be doing anything specific that has to be done on the proxy.

**Comment by ekohl** [comment]
That's possible. That still means we can remove the username/password things and clean up a bit.

**Comment by ehelms** [comment]
Agreed. I think it would simplify things a bit to just run hammer on the server itself since I also doubt its common to install and run hammer on a proxy.

**Comment by ekohl** [comment]
Part of https://github.com/theforeman/forklift/pull/451

**Pull request closed without merging**
