### PR TITLE
Fix ipa_server deployment

### PR DESCRIPTION
**Pull request by mdellweg**
Draft pr, since it is not yet working.
But i am confident that those adjustments are needed anyway.

### CODE REVIEW

**Comment by mdellweg** [comment]
The playbook succeeded after running it by hand:
`LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory --limit centos7-freeipa-server playbooks/freeipa_server.yml`

Though `vagrant up centos7-freeipa-server --provision` fails at the first `delegate_to` task.
Any help analysing this is welcome.
@ehelms @ekohl @evgeni

**Comment by ehelms** [comment]
I tested this out and hit the following error which seems different than what you are hitting. What version of Ansible are you using?

```
TASK [freeipa_server : Run FreeIPA Install] ************************************
fatal: [centos7-freeipa-server]: FAILED! => changed=true 
  cmd: ipa-server-install -U -r EXAMPLE.COM -p changeme -a changeme
  delta: '0:01:43.269579'
  end: '2019-09-06 17:18:52.048755'
  msg: non-zero return code
  rc: 1
  start: '2019-09-06 17:17:08.779176'
  stderr: |-
    ipapython.admintool: ERROR    Command '/bin/systemctl start certmonger.service' returned non-zero exit status 1
    ipapython.admintool: ERROR    The ipa-server-install command failed. See /var/log/ipaserver-install.log for more information
  stderr_lines: <omitted>
  stdout: |2-
```

**Comment by mdellweg** [comment]
I fear, it's been to long to know the ansible version, my computer had installed.
But also i think my playbook failed at a later task.

**Comment by mdellweg** [comment]
@ehelms I believe, i fixed the `delegate_to` issue now.
The ipa-server itself fails to install now. (says it didn't start after 300s)

**Comment by ehelms** [comment]
I got past this issue by udpating the OS before hand:

```
diff --git a/playbooks/freeipa_server.yml b/playbooks/freeipa_server.yml
index 0482762..bdd8111 100644
--- a/playbooks/freeipa_server.yml
+++ b/playbooks/freeipa_server.yml
@@ -5,4 +5,5 @@
     - etc_hosts
     - epel_repositories
     - haveged
+    - update_os_packages
     - freeipa_server
```

**Comment by ehelms** [comment]
Happy to merge this since it works. I was thinking about this design a bit and wondered your thoughts. This might be more useful split into two roles and playbooks? One to allow spinning up a FreeIPA server independently, then to be able to run a playbook that configures whatever host you want as a client to that server?

**Comment by mdellweg** [comment]
Well at least that design was not part of this PR. So a little out of scope?
What do i think? I think the way it is decided that centos7-katello-nightly is the server-to-be-used is a little bit confusing. If you could specify a number of hosts that ought to be assigned to that ipa server i think having only one playbook for it is fine.

**Comment by ehelms** [comment]
Oh yea, I just wanted your thoughts and figured this was a good place to get them.

**Pull request merged**
