### PR TITLE
Add sub-man register with username/password test

### PR DESCRIPTION
**Pull request by ehelms**
This was requested by @mhulan due to a recent breakage in registering via username and password.

### CODE REVIEW

**Comment by ehelms** [comment]
Ehh, maybe? I could go either way honestly. If we used it three places, for sure clean it up.

**Comment by ekohl** [comment]
Let's stick to the rule of 3 then.

**Comment by ehelms** [comment]
https://www.youtube.com/watch?v=2AoxCkySv34

**Comment by ekohl** [comment]
Looks like this fails to properly clean it up. https://ci.theforeman.org/job/release_test_katello_nightly_el7/530/console
```
ok 18 register subscription manager with username and password
not ok 19 register subscription manager with activation key
# (in test file fb-content-katello.bats, line 154)
#   `subscription-manager list --consumed | grep "${PRODUCT}"' failed
# rc=1
# This system is currently not registered.
# rc=0
# All local data removed
# rc=70
# Validation failed: Name has already been taken
```

**Pull request merged**
