### PR TITLE
Add 2.5 to version

### PR DESCRIPTION
**Pull request by zjhuntin**

### CODE REVIEW

**Comment by zjhuntin** [comment]
[test]

**Comment by evgeni** [comment]
You'll have to update the test at https://github.com/theforeman/forklift/blob/f7fd553f962f010df41e713413e895190691577e/roles/forklift_versions/molecule/default/verify.yml#L100, as it expects 4.0-nightly is the only el8 upgrade for Katello

Setting this to 4.1 should do it
https://github.com/theforeman/forklift/blob/f7fd553f962f010df41e713413e895190691577e/roles/forklift_versions/molecule/default/verify.yml#L113

**Review by evgeni — APPROVED** [review]
I'm ok merging this to get the release going, and fixing the tests later if you want.

**Comment by zjhuntin** [comment]
@evgeni updated, thank you!

**Comment by zjhuntin** [comment]
Ready to merge

**Pull request merged**
