### PR TITLE
Drop qpid from foreman_client_repositories

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Review by evgeni — APPROVED** [review]

**Review by ekohl — COMMENTED** [review]
Don't we technically still need this for 3.7 staging repos?

**Comment by evgeni** [comment]
We don't test on el7, so nope

**Comment by ekohl** [comment]
Ah yes, we only test client repos as part of our regular pipelines.

**Review by ekohl — APPROVED** [review]
I rebased this to resolve a merge conflict.

**Pull request merged**
