### PR TITLE
drop bootstrap_vagrant.sh

### PR DESCRIPTION
**Pull request by evgeni**

### CODE REVIEW

**Comment by evgeni** [comment]
Nuking them altogether would also work just fine for me ;)

**Comment by ekohl** [comment]
@ehelms I don't think this file is used anymore. Nuke it?

**Comment by ehelms** [comment]
Umm, I still use this sometimes to do some by hand install and setup of bats. Perhaps I should get out of that habit it just works so good :)

**Comment by evgeni** [comment]
On most modern systems you can just do apt/yum/dnf install bats these days. ;)

**Comment by ehelms** [comment]
Fair enough

**Comment by ehelms** [comment]
If you are nuking the file, please update the PR so we can get it merged.

**Comment by evgeni** [comment]
changed the commit to nuke bootstrap_vagrant.sh

**Comment by ekohl** [comment]
Since bats is in Fedora, EPEL6, EPEL7 and Debian Stretch + Jessie backports I think we can change the ansible role to just install the package though we might need to enable Jessie backports first. That's useful anyway because Jessie needs it for Puppet 5.

**Comment by evgeni** [comment]
Yeah. I did not do that change yet because that would mean work for me downstream (RHEL does not ship bats, and we don't enable EPEL on Satellite boxes), but I think that's doable.

**Comment by ekohl** [comment]
We could have an ```install_package.yaml``` and ```install_git.yaml``` where Jessie could use the latter as well. Maybe you can even automatically fall back to a git install if package installation fails.

**Comment by ekohl** [comment]
I include that in https://github.com/theforeman/forklift/pull/510

**Pull request merged**
