### PR TITLE
Fix upgrade pipelines by including older var sets

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ehelms** [comment]
@evgeni This was a result of the re-factor, just fyi (found by a failing 3.8 pipeline).

@jturel Take a look

**Comment by jturel** [comment]
the pipeline proceeds to run tested with:
```
ansible-playbook pipelines/katello_upgrade_pipeline.yml -e 'forklift_state=up' -e 'katello_version=3.8'
```

Do we need the yaml for 3.6 (i think that implies testing 3.6 -> 3.7 upgrade) ?

**Comment by ehelms** [comment]
When we test upgrades we start at N - 2.

**Comment by jturel** [comment]
@ehelms please merge :)

**Comment by evgeni** [comment]
@ehelms hah, yes! I must have lost these in one of the refactoring steps I made. (Pretty sure I had 3.8 working initially)

Thank for fixing!

**Pull request merged**
